# TODO: replace Dropbox links with more trusted ones (e.g. branch with git-lfs)
version: "{branch}-{build}"

image: Visual Studio 2019

# init:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: |
      echo Downloading and installing "Lazarus win32"...
      curl -fsSL -o lazarus-win32.exe "https://www.dropbox.com/s/rydwa7b1vhi3x6a/lazarus-2.0.12-fpc-3.2.0-win32.exe?raw=1"
      lazarus-win32.exe /verysilent
      echo Downloading and installing "cross-x86_64-win64" addon...
      curl -fsSL -o lazarus-cross-x86_64-win64.exe "https://www.dropbox.com/s/bvhpsv7knbrorot/lazarus-2.0.12-fpc-3.2.0-cross-x86_64-win64-win32.exe?raw=1"
      lazarus-cross-x86_64-win64.exe /verysilent
      rmdir /S /Q c:\lazarus\docs
      rmdir /S /Q c:\lazarus\examples

build_script:
  - ps: .\build_release.ps1

after_build:
  - tree /F "Cheat Engine\bin"
  - 7z a Cheat-Engine-%APPVEYOR_REPO_COMMIT%.zip ".\Cheat Engine\bin\*" -r -x!*.dbg -x!*.o -x!*.a -x!*.ppu -x!*.or -x!*.res

test: off

artifacts:
  - path: Cheat-Engine-%APPVEYOR_REPO_COMMIT%.zip
    name: Cheat-Engine-%APPVEYOR_REPO_COMMIT%  

deploy: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
